export const ACCESS_HAS_USER_ROLE = "ACCESS_HAS_USER_ROLE";
export const ACCESS_HAS_GROUP_ROLE = "ACCESS_HAS_GROUP_ROLE";
export const ACCESS_LOADING = "ACCESS_LOADING";
export const ACCESS_ERROR = "ACCESS_ERROR";