export const FAUCET_GET_NFT = "FAUCET_GET_NFT";
export const FAUCET_CALC_REWARD = "FAUCET_CALC_REWARD";
export const FAUCET_MINT_RZR = "FAUCET_MINT_RZR";
export const FAUCET_ERROR = "FAUCET_ERROR";
export const FAUCET_LOADING = "FAUCET_LOADING";
