export const TOKENS_GET_BALANCE = "TOKENS_GET_BALANCE";
export const TOKENS_GET_WALLET_ADDRESS = "TOKENS_GET_WALLET_ADDRESS";
export const TOKENS_APPROVE = "TOKENS_APPROVE";
export const TOKENS_SEND_TRANSFER = "TOKENS_SEND_TRANSFER";
export const TOKENS_IS_APPROVED = "TOKENS_IS_APPROVED";
export const TOKENS_LOADING = "TOKENS_LOADING";
export const TOKENS_ERROR = "TOKENS_ERROR";